/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stocks/{code}/diagnosis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Diagnosis */
        get: operations["stock_diagnosis_v1_stocks__code__diagnosis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DiagnosisResult */
        DiagnosisResult: {
            stock: components["schemas"]["StockContext"];
            /** Compositescore */
            compositeScore: number;
            riskLevel: components["schemas"]["RiskLevel"];
            /** Risklabel */
            riskLabel: string;
            /** Horizontradingdays */
            horizonTradingDays: number;
            /** Excessreturnrankpercentile */
            excessReturnRankPercentile: number;
            /** Upsideprobability */
            upsideProbability: number;
            /** Expectedreturnpercent */
            expectedReturnPercent: number;
            /** Downsideriskpercent */
            downsideRiskPercent: number;
            /** Dimensions */
            dimensions: components["schemas"]["ScoreDimension"][];
            /** Explanations */
            explanations: string[];
            /** Warnings */
            warnings: string[];
            /** Modelversion */
            modelVersion: string;
            /** Dataversion */
            dataVersion: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Simulated */
            simulated: boolean;
            /** Disclaimer */
            disclaimer: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            status: components["schemas"]["ServiceState"];
            /** Serviceversion */
            serviceVersion: string;
            /** Mode */
            mode: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high";
        /** ScoreDimension */
        ScoreDimension: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Score */
            score: number;
            /** Summary */
            summary: string;
        };
        /**
         * ServiceState
         * @enum {string}
         */
        ServiceState: "ok";
        /** StockContext */
        StockContext: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_diagnosis_v1_stocks__code__diagnosis_get: {
        parameters: {
            query?: {
                name?: string | null;
            };
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
