/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stocks/{code}/diagnosis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Diagnosis */
        get: operations["stock_diagnosis_v1_stocks__code__diagnosis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/p3/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** P3 Research Demo */
        get: operations["p3_research_demo_v1_research_p3_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/p2/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** P2 Data Status */
        get: operations["p2_data_status_v1_research_p2_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/p3/real": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** P3 Research Real */
        get: operations["p3_research_real_v1_research_p3_real_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/p3/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** P3 Research Current */
        get: operations["p3_research_current_v1_research_p3_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stocks/{code}/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Research */
        get: operations["stock_research_v1_stocks__code__research_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestSummary */
        BacktestSummary: {
            /** Totalreturn */
            totalReturn: number;
            /** Maxdrawdown */
            maxDrawdown: number;
            /** Turnover */
            turnover: number;
            /** Transactioncount */
            transactionCount: number;
            /** Blockedordercount */
            blockedOrderCount: number;
            /** Finalequity */
            finalEquity: number;
        };
        /** CurrentSignalHolding */
        CurrentSignalHolding: {
            /** Code */
            code: string;
            /** Rank */
            rank: number;
            /** Rankpercentile */
            rankPercentile: number;
            /** Score */
            score: number;
            /** Weight */
            weight: number | null;
        };
        /** CurrentSignalReport */
        CurrentSignalReport: {
            /** Status */
            status: string;
            /** Dataversion */
            dataVersion: string;
            /** Modelversion */
            modelVersion: string;
            /**
             * Signaldate
             * Format: date
             */
            signalDate: string;
            /**
             * Trainingstartdate
             * Format: date
             */
            trainingStartDate: string;
            /**
             * Trainingenddate
             * Format: date
             */
            trainingEndDate: string;
            /** Trainingsamplecount */
            trainingSampleCount: number;
            /** Universecount */
            universeCount: number;
            /** Rankings */
            rankings: components["schemas"]["CurrentSignalHolding"][];
            /** Eligiblefordefault */
            eligibleForDefault: boolean;
            /** Admissionreasons */
            admissionReasons: string[];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Disclaimer */
            disclaimer: string;
        };
        /** DiagnosisResult */
        DiagnosisResult: {
            stock: components["schemas"]["StockContext"];
            /** Compositescore */
            compositeScore: number;
            riskLevel: components["schemas"]["RiskLevel"];
            /** Risklabel */
            riskLabel: string;
            /** Horizontradingdays */
            horizonTradingDays: number;
            /** Excessreturnrankpercentile */
            excessReturnRankPercentile: number;
            /** Upsideprobability */
            upsideProbability: number;
            /** Expectedreturnpercent */
            expectedReturnPercent: number;
            /** Downsideriskpercent */
            downsideRiskPercent: number;
            /** Dimensions */
            dimensions: components["schemas"]["ScoreDimension"][];
            /** Explanations */
            explanations: string[];
            /** Warnings */
            warnings: string[];
            /** Modelversion */
            modelVersion: string;
            /** Dataversion */
            dataVersion: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Simulated */
            simulated: boolean;
            /** Disclaimer */
            disclaimer: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            status: components["schemas"]["ServiceState"];
            /** Serviceversion */
            serviceVersion: string;
            /** Mode */
            mode: string;
        };
        /** P2DataQuality */
        P2DataQuality: {
            /** Errors */
            errors: string[];
            /** Warnings */
            warnings: string[];
            /** Droppeddates */
            droppedDates: number;
            /** Droppedrows */
            droppedRows: number;
            /** Imputedvalues */
            imputedValues: number;
        };
        /** P2DataReport */
        P2DataReport: {
            /** Status */
            status: string;
            /** Providerid */
            providerId: string;
            /** Usagescope */
            usageScope: string;
            /** Dataversion */
            dataVersion: string;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
            /** Indexcode */
            indexCode: string;
            /** Universecount */
            universeCount: number;
            /** Tradingdays */
            tradingDays: number;
            /** Stockbarcount */
            stockBarCount: number;
            /** Financialrecordcount */
            financialRecordCount: number;
            /** Factorrows */
            factorRows: number;
            /** Factordates */
            factorDates: number;
            /** Featurenames */
            featureNames: string[];
            /** Pointintimeenforced */
            pointInTimeEnforced: boolean;
            /** Universesurvivorshipsafe */
            universeSurvivorshipSafe: boolean;
            quality: components["schemas"]["P2DataQuality"];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Disclaimer */
            disclaimer: string;
        };
        /** P3ResearchReport */
        P3ResearchReport: {
            /** Status */
            status: string;
            /** Simulated */
            simulated: boolean;
            /** Dataversion */
            dataVersion: string;
            /** Featurenames */
            featureNames: string[];
            /** Walkforwardfolds */
            walkForwardFolds: number;
            /** Embargotradingdays */
            embargoTradingDays: number;
            /** Modelresults */
            modelResults: components["schemas"]["RankingMetricResult"][];
            /** Latesttop20 */
            latestTop20: components["schemas"]["PortfolioHoldingResult"][];
            backtest: components["schemas"]["BacktestSummary"];
            /** Coveredconstraints */
            coveredConstraints: string[];
            /** Defaultmodel */
            defaultModel: string | null;
            /**
             * Latestsignaldate
             * Format: date
             */
            latestSignalDate: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Disclaimer */
            disclaimer: string;
        };
        /** PortfolioHoldingResult */
        PortfolioHoldingResult: {
            /** Code */
            code: string;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
        };
        /** RankingMetricResult */
        RankingMetricResult: {
            /** Modelversion */
            modelVersion: string;
            /** Dataversion */
            dataVersion: string;
            /**
             * Predictedat
             * Format: date-time
             */
            predictedAt: string;
            /** Rankic */
            rankIc: number;
            /** Icir */
            icir: number;
            /** Topgroupmeanexcessreturn */
            topGroupMeanExcessReturn: number;
            /** Topgroupcumulativeexcessreturn */
            topGroupCumulativeExcessReturn: number;
            /** Topgroupmaxdrawdown */
            topGroupMaxDrawdown: number;
            /** Topgroupindividualpositiveexcessrate */
            topGroupIndividualPositiveExcessRate: number;
            /** Topgroupdailypositiveexcessrate */
            topGroupDailyPositiveExcessRate: number;
            /** Evaluateddates */
            evaluatedDates: number;
            /** Eligiblefordefault */
            eligibleForDefault: boolean;
            /** Admissionreasons */
            admissionReasons: string[];
        };
        /**
         * ResearchCoverage
         * @enum {string}
         */
        ResearchCoverage: "selected_top20" | "covered_not_selected" | "not_covered";
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high";
        /** ScoreDimension */
        ScoreDimension: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Score */
            score: number;
            /** Summary */
            summary: string;
        };
        /**
         * ServiceState
         * @enum {string}
         */
        ServiceState: "ok";
        /** StockContext */
        StockContext: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** StockResearchView */
        StockResearchView: {
            stock: components["schemas"]["StockContext"];
            coverage: components["schemas"]["ResearchCoverage"];
            /** Coveragelabel */
            coverageLabel: string;
            /** Iscurrentsignal */
            isCurrentSignal: boolean;
            /** Signalagedays */
            signalAgeDays: number;
            /**
             * Signaldate
             * Format: date
             */
            signalDate: string;
            /**
             * Trainingstartdate
             * Format: date
             */
            trainingStartDate: string;
            /**
             * Trainingenddate
             * Format: date
             */
            trainingEndDate: string;
            /** Currentrank */
            currentRank: number | null;
            /** Currentscore */
            currentScore: number | null;
            /** Rankpercentile */
            rankPercentile: number | null;
            /** Top20Rank */
            top20Rank: number | null;
            /** Top20Score */
            top20Score: number | null;
            /** Top20Weight */
            top20Weight: number | null;
            /** Modelversion */
            modelVersion: string;
            /** Dataversion */
            dataVersion: string;
            /** Datastartdate */
            dataStartDate: string;
            /** Dataenddate */
            dataEndDate: string;
            /** Universecount */
            universeCount: number;
            /** Factordates */
            factorDates: number;
            /** Rankic */
            rankIc: number;
            /** Icir */
            icir: number;
            /** Topgroupdailypositiveexcessrate */
            topGroupDailyPositiveExcessRate: number;
            /** Topgroupmeanexcessreturn */
            topGroupMeanExcessReturn: number;
            /** Topgroupmaxdrawdown */
            topGroupMaxDrawdown: number;
            /** Eligiblefordefault */
            eligibleForDefault: boolean;
            /** Admissionreasons */
            admissionReasons: string[];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Disclaimer */
            disclaimer: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_diagnosis_v1_stocks__code__diagnosis_get: {
        parameters: {
            query?: {
                name?: string | null;
            };
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    p3_research_demo_v1_research_p3_demo_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["P3ResearchReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    p2_data_status_v1_research_p2_status_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["P2DataReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    p3_research_real_v1_research_p3_real_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["P3ResearchReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    p3_research_current_v1_research_p3_current_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentSignalReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_research_v1_stocks__code__research_get: {
        parameters: {
            query?: {
                name?: string | null;
            };
            header?: {
                "X-Quant-Session"?: string | null;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResearchView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
